[variables]
main_domain = "${domain}"
api_domain = "${domain}"
db_password = "${password}"
cookie_secret = "${base64:32}"
redis_password = "${password}"

[config]
[[config.mounts]]
filePath = "clickhouse/clickhouse-config.xml"
content = """
    <clickhouse>
        <logger>
            <level>warning</level>
            <console>true</console>
        </logger>
        <keep_alive_timeout>10</keep_alive_timeout>
        <!-- Stop all the unnecessary logging -->
        <query_thread_log remove="remove"/>
        <query_log remove="remove"/>
        <text_log remove="remove"/>
        <trace_log remove="remove"/>
        <metric_log remove="remove"/>
        <asynchronous_metric_log remove="remove"/>
        <session_log remove="remove"/>
        <part_log remove="remove"/>
        <listen_host>0.0.0.0</listen_host>
        <interserver_listen_host>0.0.0.0</interserver_listen_host>
        <interserver_http_host>opch</interserver_http_host>
        <!-- Disable cgroup memory observer -->
        <cgroups_memory_usage_observer_wait_time>0</cgroups_memory_usage_observer_wait_time>
        <!-- Not used anymore, but kept for backwards compatibility -->
        <macros>
            <shard>1</shard>
            <replica>replica1</replica>
            <cluster>openpanel_cluster</cluster>
        </macros>
    </clickhouse>
"""

[[config.mounts]]
filePath = "clickhouse/clickhouse-user-config.xml"
content = """
    <clickhouse>
        <profiles>
        <default>
            <log_queries>0</log_queries>
            <log_query_threads>0</log_query_threads>
        </default>
    </profiles>
    </clickhouse>
"""

[[config.mounts]]
filePath = "clickhouse/init-db.sql"
content = """
CREATE DATABASE IF NOT EXISTS openpanel;
"""

[[config.domains]]
serviceName = "op-dashboard"
port = 3_000
host = "${main_domain}"

[[config.domains]]
serviceName = "op-api"
port = 3_000
host = "${api_domain}"

[config.env]
SERVICE_FQDN_OPDASHBOARD = "http://${main_domain}"
SERVICE_FQDN_OPAPI = "http://${api_domain}"
OPENPANEL_POSTGRES_DB = "openpanel-db"
SERVICE_USER_POSTGRES = "openpanel"
SERVICE_PASSWORD_POSTGRES = "${db_password}"
SERVICE_PASSWORD_REDIS = "${redis_password}"
SERVICE_BASE64_COOKIESECRET = "${cookie_secret}"
OP_WORKER_REPLICAS = "1"

RESEND_API_KEY = ""
OPENPANEL_ALLOW_REGISTRATION = "true"
OPENPANEL_ALLOW_INVITATION = "true"
