services:
  directory-lister:
    image: directorylister/directorylister:latest
    restart: unless-stopped
    ports:
      # The internal port of the application.
      - 80
    volumes:
      # Mounts a persistent named volume to store directory data.
      - directory-lister-data:/data

volumes:
  # Defines the Docker-managed volume for data persistence.
  directory-lister-data: {}
