version: "3.8"
services:
  dumbbudget:
    image: dumbwareio/dumbbudget:latest
    restart: unless-stopped
    ports:
      - 3000
    volumes:
      - dumbbudget-data:/app/data

volumes:
  dumbbudget-data: {}
